"""empty message

Revision ID: a63b27f612f0
Revises: 9cf53a21e2b8
Create Date: 2024-01-15 00:15:39.416404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63b27f612f0'
down_revision = '9cf53a21e2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview', sa.String(length=3000), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=3000), autoincrement=False, nullable=False))
        batch_op.drop_column('overview')

    # ### end Alembic commands ###
