"""empty message

Revision ID: de908992fd38
Revises: a63b27f612f0
Create Date: 2024-01-15 01:36:38.561971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de908992fd38'
down_revision = 'a63b27f612f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adult', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('genre_ids', sa.String(length=3000), nullable=False))
        batch_op.add_column(sa.Column('original_language', sa.String(length=3000), nullable=False))
        batch_op.add_column(sa.Column('original_title', sa.String(length=3000), nullable=False))
        batch_op.add_column(sa.Column('video', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('vote_count')
        batch_op.drop_column('video')
        batch_op.drop_column('original_title')
        batch_op.drop_column('original_language')
        batch_op.drop_column('genre_ids')
        batch_op.drop_column('adult')

    # ### end Alembic commands ###
